{% set version = "2023.3.2" %}


package:
  name: dask-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 51009e92ba9a280bd417633d1ae84f3ed23a8940f0a19594a4b7797ef226fff4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask = dask.__main__:main

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - click >=7.0
    - cloudpickle >=1.1.1
    - fsspec >=0.6.0
    - packaging >=20.0
    - partd >=1.2.0
    - pyyaml >=5.3.1
    - toolz >=0.8.2
    - importlib_metadata >=4.13.0

test:
  imports:
    - dask
  commands:
    - pip check
    - dask docs --help
    - dask info --help
    - dask info versions --help
  requires:
    - pip

about:
  home: https://github.com/dask/dask/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  summary: Parallel Python with task scheduling
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
    - charlesbluca 
